[package]
name = "rio-rs"
version = "0.1.0"
edition = "2018"
default-run = "main"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
threadpool = "1.0"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "main"
path = "src/main.rs"
