[workspace]
members = [
    "rio-rs",
    "rio-macros",
    "examples/black-jack",
    "examples/metric-aggregator",
    "examples/ping-pong",
    "examples/presence",
    "examples/custom-storage",
]
resolver = "2"
