[workspace]
members = [
    "rio-rs",
    "rio-macros",
    "examples/black-jack",
    "examples/metric-aggregator",
    "examples/ping-pong",
    "examples/presence", "examples/black-jack-ffi", "examples/black-jack-wasm", "examples/wasm-registry",
]
resolver = "2"
