#!/usr/bin/env bash

docker compose -f compose-cockroach.yaml up -d --wait
sleep 10
echo Run the client with the command:
echo cargo run --bin client -- -c postgres://root@localhost:26257/defaultdb CLIENT_001
cargo run --bin server -- -c postgres://root@localhost:26257/defaultdb \
                          -o postgres://root@localhost:26257/defaultdb \
                          -s postgres://root@localhost:26257/defaultdb  \
                          9999
