[package]
name = "example-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
bincode = "1.3.3"
rio-rs = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
