services:
  silo:
    image: rio-rs
    build: ../../
    command: server 0.0.0.0:5000
    volumes:
      - "/tmp/membership.sqlite3:/tmp/membership.sqlite3"
      - "/tmp/placement.sqlite3:/tmp/placement.sqlite3"

  load_client:
    image: rio-rs
    scale: 0
    build: ../../
    command: ["load_client", "sqlite:///tmp/membership.sqlite3", "1", "10"]
    volumes:
      - "/tmp/membership.sqlite3:/tmp/membership.sqlite3"
