help:
    just --list

# Install required tools
tools:
	cargo install flamegraph

loadserver:
	cargo build --release
	valgrind --leak-check=full ../../target/release/metric_aggregator_server 0.0.0.0:5000

flamegraph-server:
	CARGO_PROFILE_RELEASE_DEBUG=true cargo flamegraph --bin metric_aggregator_server --  0.0.0.0:5000

loadall:
	cargo run --bin metric_aggregator_loadall

dropall:
	cargo run --bin metric_aggregator_dropall
