name: Rust
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check

  check:
    runs-on: ubuntu-latest
    needs: [quick-check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Fmt
        run: cargo fmt -- --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy
      - name: Docs
        run: cargo doc -p rio-rs -p rio-macros --no-deps

  test:
    runs-on: ubuntu-latest
    needs: [quick-check]
    services:
      redis:
        image: valkey/valkey:7.2.7-alpine
        ports:
          - 16379:6379
      pgsql:
        image: postgres:16.4
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 15432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install nextest
        run: cargo install cargo-nextest
      - name: Tests
        run: cargo nextest run --config-file .config/nextest.ci.toml

  build:
    runs-on: ubuntu-latest
    needs: [quick-check]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --verbose
